platform :ios, '5.0'

pod 'PeakCategory', :git => 'git@github.com:conis/PeakCategory.git', :branch => 'master'
pod 'KKGestureLockView',  :git => 'https://github.com/kejinlu/KKGestureLockView.git', :branch => 'master'
xcodeproj 'PeakLocker-Samples.xcodeproj'

